#!/bin/bash

SIMNAME="$1"
TOPLEVEL_FILE="$(readlink -f "sim/$SIMNAME/"*.sv)"
SIMSRCS="$(find "$(readlink -e "sim/$SIMNAME")" -name '*.cpp')"
OUTDIR="build/$SIMNAME"
TOPLEVEL_FILE_NAME="${TOPLEVEL_FILE##*/}"
TOPLEVEL_NAME="${TOPLEVEL_FILE_NAME%.sv}"

set -ex
mkdir -p "$OUTDIR"
verilator \
    -Wall \
    --Mdir "$OUTDIR" \
    --cc \
    "$TOPLEVEL_FILE" \
    --exe \
    $VERILATOR_FLAGS \
    $SIMSRCS
make -C "$OUTDIR" -f "V${TOPLEVEL_NAME}.mk" CC="$CC" CXX="$CXX" LINK="$LD"
exec "$OUTDIR/V$TOPLEVEL_NAME"
